model_name: MedSAM
training_state: frozen

medsam_repo_root: "C:\\Users\\cooll\\OneDrive\\Documents\\SPARC\\Models\\MedSAM\\MedSAM"
checkpoint: "C:\\Users\\cooll\\OneDrive\\Documents\\SPARC\\SAM checkpoints\\medsam_vit_b.pth"

device: "cuda"
image_size: 1024