model_name: SAM-Med2D
training_state: frozen

sammed2d_repo_root: "C:\\Users\\cooll\\OneDrive\\Documents\\SPARC\\Models\\SAM-Med2d\\SAM-Med2D"
checkpoint: "C:\\Users\\cooll\\OneDrive\\Documents\\SPARC\\SAM Checkpoints\\sam-med2d_b.pth"

device: "cuda"
model_type: "vit_b"
image_size: 256
encoder_adapter: true
multimask_output: true
mask_selection: "highest_score"