model_name: SegFormer
training_state: trained

architecture: "SegFormer"
pretrained_model_name: "nvidia/segformer-b2-finetuned-ade-512-512"

num_labels: 1

image_size: 512
batch_size: 4
num_workers: 4

epochs: 100
learning_rate: 0.00006
weight_decay: 0.00001

loss:
  dice_weight: 0.5
  bce_weight: 0.5

threshold: 0.5
device: "cuda"

postprocessing:
  remove_small_components: false
  min_component_area_px: 0

threshold_sweep:
  enabled: true
  values: [0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]
  choose_metric: "dice"
  use_best_threshold_for_final_eval: false

scheduler:
  use_reduce_on_plateau: true
  factor: 0.5
  patience: 8
  min_lr: 0.000001

early_stopping:
  enabled: true
  patience: 20
  min_delta: 0.001