model_name: SurgiSAM2
training_state: frozen

sam2_repo_root: "C:\\Users\\cooll\\OneDrive\\Documents\\SPARC\\Models\\SAM2\\sam2"
#surgisam2_repo_root: "F:/Models/SurgiSAM2"

checkpoint: "C:\\Users\\cooll\\OneDrive\\Documents\\SPARC\\SAM checkpoints\\Curated400_checkpoint_26.pt"

# This worked in your install test.
model_cfg: "C:\\Users\\cooll\\OneDrive\\Documents\\SPARC\\Models\\SAM2\\sam2\\sam2\\configs\\sam2.1\\sam2.1_hiera_b+.yaml"

device: "cuda"
multimask_output: true
mask_selection: "highest_score"
use_bfloat16: true